### ISSUE TITLE
Additional data sources [side-tracked]

### ISSUE THREAD

**Issue by Torvaney** [Torvaney/ggsoccer#12]
* TRACAB
* Wyscout

**Comment by Zuhgoh** [comment]
Please, i dont know if it s possible but could you help me. I try to use ggsoccer...I m not an expert, i discovered R, and i would like put on the map the mean position of my player. The GPS give me position X and Y. But the max X is 100 and the max Y is 64... How can i change with theme_pitch(). Thanks for you answer
Have a nice day

**Comment by Torvaney** [comment]
Hey @Zuhgoh - it sounds like you are using a new data source that's not present in the package. Fortunately, if you know the dimensions of your data source, this is relatively easy to do!

You just need to create a new list containing the dimensions of your data source like the ones found here: https://github.com/Torvaney/ggsoccer/blob/master/R/dimensions.R

```r
# fill in ??? with your data's dimensions 
pitch_zuhgoh <- list(
  length = 100,
  width = 64,
  penalty_box_length = ???,
  penalty_box_width = ???,
  six_yard_box_length = ???,
  six_yard_box_width = ???,
  penalty_spot_distance = ???,
  goal_width = ???,
  origin_x = ???,
  origin_y = ???
)
```

Then you can supply this list as an argument to `annotate_pitch`:

```r
ggplot() +
  annotate_pitch(dimensions = pitch_zuhgoh) +
  theme_pitch() +
  # ... etc
```

**Comment by Zuhgoh** [comment]
Thank youuuuuuuuuuuuuuuuuuuuuuuuuuu

If i ve got other question, can i ask you? I m new and i try to learn this
new world for me....
Thanks

Le jeu. 19 mars 2020 à 13:14, Ben Torvaney <notifications@github.com> a
écrit :

**Comment by Zuhgoh** [comment]
Just one question, since i try with "my field", i can t see my plot...
Could you help me?

**Comment by Zuhgoh** [comment]
Sorry, now all is ok... just a question, how can i do for put numbers with
","... for example 42,12? Because R tell me "Error in data.frame(x = c(41,
8, 52, 7, 57, 2), y = c(50.2, 16, 5, 33)) :
  les arguments impliquent des nombres de lignes différents : 6, 4"

Sorry sorry and thanks thanks

**Comment by Zuhgoh** [comment]
Sorry,

I ve got a question, the last... it s possible to change the field and put
the pitcure in files attachement?

Thanks

Le jeu. 19 mars 2020 à 13:14, Ben Torvaney <notifications@github.com> a
écrit :

**Comment by Torvaney** [comment]
> Sorry, now all is ok... just a question, how can i do for put numbers with
","... for example 42,12? Because R tell me "Error in data.frame(x = c(41,
8, 52, 7, 57, 2), y = c(50.2, 16, 5, 33)) :
  les arguments impliquent des nombres de lignes différents : 6, 4"

This is because your x and y vectors (arguments to `data.frame`) have different lengths.

> I ve got a question, the last... it s possible to change the field and put
the pitcure in files attachement?

I'm not sure what you mean here, I'm afraid.

In future, if you need more general R help, including setting up RStudio and the like, you may get more timely useful answers on other forums. https://community.rstudio.com/ tends to be quite friendly and helpful. https://stackoverflow.com/ is another option, but is less beginner-friendly.
