### ISSUE TITLE
I dont know how I can do this, but with otre link please hel pme!

### ISSUE THREAD

**Issue by esacosta1** [Torvaney/ggsoccer#14]
url <- "https://es.wikipedia.org/wiki/Anexo:Estad%C3%ADsticas_de_la_Copa_Am%C3%A9rica"

session <- bow(url)

copa_top_scorers <- scrape(session) %>% 
  html_nodes(".mw-parser-output > table:nth-child(95)") %>% 
  html_table() %>% 
  flatten_df() %>% 
  set_names(c("player", "country", "goals")) %>% 
  mutate(image = "https://www.emoji.co.uk/files/microsoft-emojis/activity-windows10/8356-soccer-ball.png")

I want to do with this https://es.wikipedia.org/wiki/Clasificaci%C3%B3n_de_Conmebol_para_la_Copa_Mundial_de_F%C3%BAtbol_de_2018#Goleadores

**Comment by Torvaney** [comment]
Hey - it looks like this is an issue unrelated to this package, perhaps with web scraping. If you are looking for more general R help like this, you're probably better off asking on https://community.rstudio.com/ or on https://stackoverflow.com/
