### ISSUE TITLE
rescale_coordinates function not found

### ISSUE THREAD

**Issue by FranGoitia** [Torvaney/ggsoccer#16]
I think there is an issue with the rescale_coordinates function as it is not currently found when you try to use it after loading the package the standard way of `library(ggsoccer)`

**Comment by FranGoitia** [comment]
The issue is only affecting the package in CRAN

**Comment by Torvaney** [comment]
Hey! Yes, I believe the `rescale_coordinates` function was not included in the CRAN release (the github version is ahead of the CRAN version), so you must install from github to use this function (or wait for another CRAN release - although I wouldn't recommend that :) )
