### ISSUE TITLE
international pitch dimension size

### ISSUE THREAD

**Issue by RobWHickman** [Torvaney/ggsoccer#20]
Forgive me if I'm wrong as I'm quite likely to be, but as I understand it, the commonly used default international pitch size is 105x68m and not 100x68m as specified in
https://github.com/Torvaney/ggsoccer/blob/c99d76d9060207a5e078839ba9cf1009fbe71a2e/R/dimensions.R#L96

(this would make my life one line of code easier as at the moment I'm basing everything I do on socceraction's definition of the pitch being that size)

I'll stick a pull request in case it's a typo, but obviously ignore if it isn't

(I did notice Marek's tracab function just stretches this which lends some support to it being intentional)

**Comment by RobWHickman** [comment]
(also the citation in that function doesn't work for me but I'm on holiday inn wifi so it could just be that, I'll also stick a new one in the PR just in case)

**Comment by Torvaney** [comment]
Yep, I think this is a typo. I've used 105x68 everywhere else, like in the fixed aspect ratio
