### ISSUE TITLE
Allow user to pass in `size` for the lines in `annotate_pitch`

### ISSUE THREAD

**Issue by lvanden** [Torvaney/ggsoccer#23]
This would just be a `nice-to-have` addition. It wouldn't be too difficult and I'm happy to help if needed.

**Comment by Torvaney** [comment]
This is a good idea and long overdue; I think in general the aesthetics for the pitch elements should be available for the end-user. In practice, I think this just means adding support for `size`, `alpha`, and `

**Comment by lvanden** [comment]
Sounds good. I'm happy to review if you'd like another pair of eyes. Thanks for doing this!

**Comment by Torvaney** [comment]
No problem!

**Comment by Torvaney** [comment]
Noting for myself to check later: I think using `ggforce::geom_arc` (or creating an analogous custom geom) for the annotations (as opposed to grobs) would facilitate this.
