### ISSUE TITLE
Annotate pitch, rectangles not appearing

### ISSUE THREAD

**Issue by rblay** [Torvaney/ggsoccer#9]
Hello, big fan of this project! I tried to use it on some data and the annotate_pitch seems not to be working properly. I'm not sure if it is some issue with my R or ggplot2 version. Here is a picture of what is being displayed with `ggplot() + annotate_pitch()`:
<img width="826" alt="screen shot 2018-12-15 at 2 33 56 pm" src="https://user-images.githubusercontent.com/11521028/50045269-e931b280-0076-11e9-9dc5-b70c3edbba20.png">

**Comment by rblay** [comment]
@Torvaney What I did to solve the issue was to make some slight edits on the `annotate_pitch()` function. I simply altered the `ggplot::geom_rect()` calls with `ggplot:annotate()` cals and added a `geom = 'rect'` to the arguments. I'll do a pull request with that if necessary. Best!

**Comment by rblay** [comment]
I tried to reproduce the error but now it seems to work. I'll post the reprex and make the PR if it reoccurs!

**Comment by Torvaney** [comment]
Ah sorry, I think this issue got closed by https://github.com/Torvaney/ggsoccer/commit/b6b2aaba2ab1737502d5237f7f4694a2d0d81189
